package DataDictionaryDsl.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import DataDictionaryDsl.behavior.DataDictionary__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class quick_fix_unique_structure_name_QuickFix extends QuickFix_Runtime {
  public quick_fix_unique_structure_name_QuickFix() {
    super(new SNodePointer("r:98240634-8132-4253-b351-9c7ee2a54fa8(DataDictionaryDsl.typesystem)", "547209407214662347"));
  }
  public String getDescription(SNode node) {
    return "Quick fix unique structure name";
  }
  public void execute(SNode node) {
    Integer size = ListSequence.fromList(SLinkOperations.getChildren(SNodeOperations.getNodeAncestor(((SNode) quick_fix_unique_structure_name_QuickFix.this.getField("nodeStructureDef")[0]), MetaAdapterFactory.getConcept(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x73ede05be9bfff49L, "DataDictionaryDsl.structure.DataDictionary"), false, false), MetaAdapterFactory.getContainmentLink(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x73ede05be9bfff49L, 0x73ede05be9bfff4cL, "structures"))).count();
    while (DataDictionary__BehaviorDescriptor.ifExistStructureName_iduo50TYOm6l.invoke(SNodeOperations.getNodeAncestor(((SNode) quick_fix_unique_structure_name_QuickFix.this.getField("nodeStructureDef")[0]), MetaAdapterFactory.getConcept(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x73ede05be9bfff49L, "DataDictionaryDsl.structure.DataDictionary"), false, false), "Structure " + size)) {
      size++;
    }
    SPropertyOperations.assign(((SNode) quick_fix_unique_structure_name_QuickFix.this.getField("nodeStructureDef")[0]), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Structure " + size);
  }
}
