package DataDictionaryDsl.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;

public class quick_fix_aggregation_inside_set_QuickFix extends QuickFix_Runtime {
  public quick_fix_aggregation_inside_set_QuickFix() {
    super(new SNodePointer("r:98240634-8132-4253-b351-9c7ee2a54fa8(DataDictionaryDsl.typesystem)", "4369699962420967484"));
  }
  public String getDescription(SNode node) {
    return "Quick fix more than one element in set";
  }
  public void execute(SNode node) {
    SNode aggregation = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x73ede05be9c14454L, "DataDictionaryDsl.structure.Aggregation"));
    for (SNode element : SLinkOperations.getChildren(((SNode) quick_fix_aggregation_inside_set_QuickFix.this.getField("set")[0]), MetaAdapterFactory.getContainmentLink(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873e5L, 0x7171b68977873e9L, "elements"))) {
      ListSequence.fromList(SLinkOperations.getChildren(aggregation, MetaAdapterFactory.getContainmentLink(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873e5L, 0x7171b68977873e9L, "elements"))).addElement(element);
    }
    ListSequence.fromList(SLinkOperations.getChildren(((SNode) quick_fix_aggregation_inside_set_QuickFix.this.getField("set")[0]), MetaAdapterFactory.getContainmentLink(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873e5L, 0x7171b68977873e9L, "elements"))).clear();
    ListSequence.fromList(SLinkOperations.getChildren(((SNode) quick_fix_aggregation_inside_set_QuickFix.this.getField("set")[0]), MetaAdapterFactory.getContainmentLink(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873e5L, 0x7171b68977873e9L, "elements"))).addElement(aggregation);

  }
}
