package DataDictionaryDsl.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AbstractDomain = 0;
  public static final int Aggregation = 1;
  public static final int Boolean = 2;
  public static final int Constraint = 3;
  public static final int DataDictionary = 4;
  public static final int Date = 5;
  public static final int Double = 6;
  public static final int Exclusive = 7;
  public static final int Field = 8;
  public static final int FieldDefinition = 9;
  public static final int IAbstractElement = 10;
  public static final int IAbstractStructure = 11;
  public static final int ISpecialization = 12;
  public static final int Integer = 13;
  public static final int NonExclusive = 14;
  public static final int PredefinedDomain = 15;
  public static final int SemanticDomain = 16;
  public static final int SemanticDomainDefinition = 17;
  public static final int Set = 18;
  public static final int StructureDefinition = 19;
  public static final int Text = 20;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x16d63821a9174aafL, 0xa85f305cd4a0013fL);
    builder.put(0x160766bd43386035L, AbstractDomain);
    builder.put(0x73ede05be9c14454L, Aggregation);
    builder.put(0x160766bd43386049L, Boolean);
    builder.put(0x605f2c5169ea95c5L, Constraint);
    builder.put(0x73ede05be9bfff49L, DataDictionary);
    builder.put(0x356f836ebb6d8790L, Date);
    builder.put(0x160766bd43386048L, Double);
    builder.put(0x7171b68977873f0L, Exclusive);
    builder.put(0x73ede05be9c14433L, Field);
    builder.put(0x160766bd4338602aL, FieldDefinition);
    builder.put(0x7171b68977873e6L, IAbstractElement);
    builder.put(0x7171b68977873e5L, IAbstractStructure);
    builder.put(0x7171b68977873efL, ISpecialization);
    builder.put(0x160766bd43386039L, Integer);
    builder.put(0x73ede05be9c1bfe4L, NonExclusive);
    builder.put(0x160766bd43386038L, PredefinedDomain);
    builder.put(0x160766bd43386032L, SemanticDomain);
    builder.put(0x3ca44af6d3197f9aL, SemanticDomainDefinition);
    builder.put(0x73ede05be9c14455L, Set);
    builder.put(0x73ede05be9bfff46L, StructureDefinition);
    builder.put(0x160766bd4338604aL, Text);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
